esphome:
  name: temp_bathroom
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: !secret ssid
  password: !secret wifi_password
    # Optional manual IP
  manual_ip:
    static_ip: 192.168.2.216
    gateway: 192.168.2.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temp-Bathroom Fallback Hotspot"
    password: "RxcmiuCeoF75"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "password"

ota:
  safe_mode: True
  password: "password"

i2c: 
  sda: D2 
  scl: D1

sensor:
  - platform: bme280
    temperature:
      name: "Bathroom Temperature"
      oversampling: 16x
      filters:
       - offset: -4.9
    pressure:
      name: "Bathroom Pressure"
    humidity:
      name: "Bathroom Humidity"
    address: 0x76
    #then:
      #- deep_sleep.enter: deep_sleep_1
    update_interval: 30s
#deep_sleep:
  #run_duration: 5min
  #sleep_duration: 10min